spring:
  application:
    name: eurekaserver

server:
  port: 8762
 # ssl:
 #  key-alias:  employeemgmt
 #  key-store:  classpath:valuela.jks
 #  key-store-type: JKS
 #  key-password: changeit
 #  trust-store: classpath:valuela.jks
 #  trust-store-type: PKCS12
 #  trust-store-password: changeit


eureka:
  instance:
#nonSecurePortEnabled: false
 #   securePortEnabled: true
    hostname: localhost
    
  client:
   register-with-eureka: false
   fetch-registry: false
  
   serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}/${server.port}/eureka

management:
 endpoints:
    web:
      exposure:
        include: true

