app:
 security:
  jwt:
   keystore-location: keys/keystore.jks
   keystore-password: password
   key-alias: jwtsigning
   private-key-passphrase: password
   
   
spring:
 application:
    name: registration
 datasource:
  url : jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  
  
 h2:
  console:
   enabled: true

    
server:
 port: 8081
 
# ssl:
 #   key-alias:  employeemgmt
 #   key-store:  classpath:valuela.jks
 #   key-store-type: JKS
 #   key-password: changeit
 
eureka:
  instance:
    prefer-ip-address: true
    
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone:  http://localhost:8762/eureka/


 
